/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package test.prof.events;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ProfileEventHeader extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3116974614175757044L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ProfileEventHeader\",\"namespace\":\"test.prof.events\",\"fields\":[{\"name\":\"headerVersion\",\"type\":\"string\"},{\"name\":\"messageId\",\"type\":\"string\"},{\"name\":\"aggregateId\",\"type\":\"string\"},{\"name\":\"occurrenceDate\",\"type\":\"string\"},{\"name\":\"actor\",\"type\":\"string\"},{\"name\":\"source\",\"type\":\"string\"},{\"name\":\"eventType\",\"type\":\"string\"},{\"name\":\"eventTypeVersion\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ProfileEventHeader> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ProfileEventHeader> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ProfileEventHeader> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ProfileEventHeader> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ProfileEventHeader> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ProfileEventHeader to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ProfileEventHeader from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ProfileEventHeader instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ProfileEventHeader fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence headerVersion;
  private java.lang.CharSequence messageId;
  private java.lang.CharSequence aggregateId;
  private java.lang.CharSequence occurrenceDate;
  private java.lang.CharSequence actor;
  private java.lang.CharSequence source;
  private java.lang.CharSequence eventType;
  private java.lang.CharSequence eventTypeVersion;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ProfileEventHeader() {}

  /**
   * All-args constructor.
   * @param headerVersion The new value for headerVersion
   * @param messageId The new value for messageId
   * @param aggregateId The new value for aggregateId
   * @param occurrenceDate The new value for occurrenceDate
   * @param actor The new value for actor
   * @param source The new value for source
   * @param eventType The new value for eventType
   * @param eventTypeVersion The new value for eventTypeVersion
   */
  public ProfileEventHeader(java.lang.CharSequence headerVersion, java.lang.CharSequence messageId, java.lang.CharSequence aggregateId, java.lang.CharSequence occurrenceDate, java.lang.CharSequence actor, java.lang.CharSequence source, java.lang.CharSequence eventType, java.lang.CharSequence eventTypeVersion) {
    this.headerVersion = headerVersion;
    this.messageId = messageId;
    this.aggregateId = aggregateId;
    this.occurrenceDate = occurrenceDate;
    this.actor = actor;
    this.source = source;
    this.eventType = eventType;
    this.eventTypeVersion = eventTypeVersion;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return headerVersion;
    case 1: return messageId;
    case 2: return aggregateId;
    case 3: return occurrenceDate;
    case 4: return actor;
    case 5: return source;
    case 6: return eventType;
    case 7: return eventTypeVersion;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: headerVersion = (java.lang.CharSequence)value$; break;
    case 1: messageId = (java.lang.CharSequence)value$; break;
    case 2: aggregateId = (java.lang.CharSequence)value$; break;
    case 3: occurrenceDate = (java.lang.CharSequence)value$; break;
    case 4: actor = (java.lang.CharSequence)value$; break;
    case 5: source = (java.lang.CharSequence)value$; break;
    case 6: eventType = (java.lang.CharSequence)value$; break;
    case 7: eventTypeVersion = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'headerVersion' field.
   * @return The value of the 'headerVersion' field.
   */
  public java.lang.CharSequence getHeaderVersion() {
    return headerVersion;
  }


  /**
   * Sets the value of the 'headerVersion' field.
   * @param value the value to set.
   */
  public void setHeaderVersion(java.lang.CharSequence value) {
    this.headerVersion = value;
  }

  /**
   * Gets the value of the 'messageId' field.
   * @return The value of the 'messageId' field.
   */
  public java.lang.CharSequence getMessageId() {
    return messageId;
  }


  /**
   * Sets the value of the 'messageId' field.
   * @param value the value to set.
   */
  public void setMessageId(java.lang.CharSequence value) {
    this.messageId = value;
  }

  /**
   * Gets the value of the 'aggregateId' field.
   * @return The value of the 'aggregateId' field.
   */
  public java.lang.CharSequence getAggregateId() {
    return aggregateId;
  }


  /**
   * Sets the value of the 'aggregateId' field.
   * @param value the value to set.
   */
  public void setAggregateId(java.lang.CharSequence value) {
    this.aggregateId = value;
  }

  /**
   * Gets the value of the 'occurrenceDate' field.
   * @return The value of the 'occurrenceDate' field.
   */
  public java.lang.CharSequence getOccurrenceDate() {
    return occurrenceDate;
  }


  /**
   * Sets the value of the 'occurrenceDate' field.
   * @param value the value to set.
   */
  public void setOccurrenceDate(java.lang.CharSequence value) {
    this.occurrenceDate = value;
  }

  /**
   * Gets the value of the 'actor' field.
   * @return The value of the 'actor' field.
   */
  public java.lang.CharSequence getActor() {
    return actor;
  }


  /**
   * Sets the value of the 'actor' field.
   * @param value the value to set.
   */
  public void setActor(java.lang.CharSequence value) {
    this.actor = value;
  }

  /**
   * Gets the value of the 'source' field.
   * @return The value of the 'source' field.
   */
  public java.lang.CharSequence getSource() {
    return source;
  }


  /**
   * Sets the value of the 'source' field.
   * @param value the value to set.
   */
  public void setSource(java.lang.CharSequence value) {
    this.source = value;
  }

  /**
   * Gets the value of the 'eventType' field.
   * @return The value of the 'eventType' field.
   */
  public java.lang.CharSequence getEventType() {
    return eventType;
  }


  /**
   * Sets the value of the 'eventType' field.
   * @param value the value to set.
   */
  public void setEventType(java.lang.CharSequence value) {
    this.eventType = value;
  }

  /**
   * Gets the value of the 'eventTypeVersion' field.
   * @return The value of the 'eventTypeVersion' field.
   */
  public java.lang.CharSequence getEventTypeVersion() {
    return eventTypeVersion;
  }


  /**
   * Sets the value of the 'eventTypeVersion' field.
   * @param value the value to set.
   */
  public void setEventTypeVersion(java.lang.CharSequence value) {
    this.eventTypeVersion = value;
  }

  /**
   * Creates a new ProfileEventHeader RecordBuilder.
   * @return A new ProfileEventHeader RecordBuilder
   */
  public static test.prof.events.ProfileEventHeader.Builder newBuilder() {
    return new test.prof.events.ProfileEventHeader.Builder();
  }

  /**
   * Creates a new ProfileEventHeader RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ProfileEventHeader RecordBuilder
   */
  public static test.prof.events.ProfileEventHeader.Builder newBuilder(test.prof.events.ProfileEventHeader.Builder other) {
    if (other == null) {
      return new test.prof.events.ProfileEventHeader.Builder();
    } else {
      return new test.prof.events.ProfileEventHeader.Builder(other);
    }
  }

  /**
   * Creates a new ProfileEventHeader RecordBuilder by copying an existing ProfileEventHeader instance.
   * @param other The existing instance to copy.
   * @return A new ProfileEventHeader RecordBuilder
   */
  public static test.prof.events.ProfileEventHeader.Builder newBuilder(test.prof.events.ProfileEventHeader other) {
    if (other == null) {
      return new test.prof.events.ProfileEventHeader.Builder();
    } else {
      return new test.prof.events.ProfileEventHeader.Builder(other);
    }
  }

  /**
   * RecordBuilder for ProfileEventHeader instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ProfileEventHeader>
    implements org.apache.avro.data.RecordBuilder<ProfileEventHeader> {

    private java.lang.CharSequence headerVersion;
    private java.lang.CharSequence messageId;
    private java.lang.CharSequence aggregateId;
    private java.lang.CharSequence occurrenceDate;
    private java.lang.CharSequence actor;
    private java.lang.CharSequence source;
    private java.lang.CharSequence eventType;
    private java.lang.CharSequence eventTypeVersion;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(test.prof.events.ProfileEventHeader.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.headerVersion)) {
        this.headerVersion = data().deepCopy(fields()[0].schema(), other.headerVersion);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.messageId)) {
        this.messageId = data().deepCopy(fields()[1].schema(), other.messageId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.aggregateId)) {
        this.aggregateId = data().deepCopy(fields()[2].schema(), other.aggregateId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.occurrenceDate)) {
        this.occurrenceDate = data().deepCopy(fields()[3].schema(), other.occurrenceDate);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.actor)) {
        this.actor = data().deepCopy(fields()[4].schema(), other.actor);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.source)) {
        this.source = data().deepCopy(fields()[5].schema(), other.source);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.eventType)) {
        this.eventType = data().deepCopy(fields()[6].schema(), other.eventType);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.eventTypeVersion)) {
        this.eventTypeVersion = data().deepCopy(fields()[7].schema(), other.eventTypeVersion);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
    }

    /**
     * Creates a Builder by copying an existing ProfileEventHeader instance
     * @param other The existing instance to copy.
     */
    private Builder(test.prof.events.ProfileEventHeader other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.headerVersion)) {
        this.headerVersion = data().deepCopy(fields()[0].schema(), other.headerVersion);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.messageId)) {
        this.messageId = data().deepCopy(fields()[1].schema(), other.messageId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.aggregateId)) {
        this.aggregateId = data().deepCopy(fields()[2].schema(), other.aggregateId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.occurrenceDate)) {
        this.occurrenceDate = data().deepCopy(fields()[3].schema(), other.occurrenceDate);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.actor)) {
        this.actor = data().deepCopy(fields()[4].schema(), other.actor);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.source)) {
        this.source = data().deepCopy(fields()[5].schema(), other.source);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.eventType)) {
        this.eventType = data().deepCopy(fields()[6].schema(), other.eventType);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.eventTypeVersion)) {
        this.eventTypeVersion = data().deepCopy(fields()[7].schema(), other.eventTypeVersion);
        fieldSetFlags()[7] = true;
      }
    }

    /**
      * Gets the value of the 'headerVersion' field.
      * @return The value.
      */
    public java.lang.CharSequence getHeaderVersion() {
      return headerVersion;
    }


    /**
      * Sets the value of the 'headerVersion' field.
      * @param value The value of 'headerVersion'.
      * @return This builder.
      */
    public test.prof.events.ProfileEventHeader.Builder setHeaderVersion(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.headerVersion = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'headerVersion' field has been set.
      * @return True if the 'headerVersion' field has been set, false otherwise.
      */
    public boolean hasHeaderVersion() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'headerVersion' field.
      * @return This builder.
      */
    public test.prof.events.ProfileEventHeader.Builder clearHeaderVersion() {
      headerVersion = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'messageId' field.
      * @return The value.
      */
    public java.lang.CharSequence getMessageId() {
      return messageId;
    }


    /**
      * Sets the value of the 'messageId' field.
      * @param value The value of 'messageId'.
      * @return This builder.
      */
    public test.prof.events.ProfileEventHeader.Builder setMessageId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.messageId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'messageId' field has been set.
      * @return True if the 'messageId' field has been set, false otherwise.
      */
    public boolean hasMessageId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'messageId' field.
      * @return This builder.
      */
    public test.prof.events.ProfileEventHeader.Builder clearMessageId() {
      messageId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'aggregateId' field.
      * @return The value.
      */
    public java.lang.CharSequence getAggregateId() {
      return aggregateId;
    }


    /**
      * Sets the value of the 'aggregateId' field.
      * @param value The value of 'aggregateId'.
      * @return This builder.
      */
    public test.prof.events.ProfileEventHeader.Builder setAggregateId(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.aggregateId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'aggregateId' field has been set.
      * @return True if the 'aggregateId' field has been set, false otherwise.
      */
    public boolean hasAggregateId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'aggregateId' field.
      * @return This builder.
      */
    public test.prof.events.ProfileEventHeader.Builder clearAggregateId() {
      aggregateId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'occurrenceDate' field.
      * @return The value.
      */
    public java.lang.CharSequence getOccurrenceDate() {
      return occurrenceDate;
    }


    /**
      * Sets the value of the 'occurrenceDate' field.
      * @param value The value of 'occurrenceDate'.
      * @return This builder.
      */
    public test.prof.events.ProfileEventHeader.Builder setOccurrenceDate(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.occurrenceDate = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'occurrenceDate' field has been set.
      * @return True if the 'occurrenceDate' field has been set, false otherwise.
      */
    public boolean hasOccurrenceDate() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'occurrenceDate' field.
      * @return This builder.
      */
    public test.prof.events.ProfileEventHeader.Builder clearOccurrenceDate() {
      occurrenceDate = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'actor' field.
      * @return The value.
      */
    public java.lang.CharSequence getActor() {
      return actor;
    }


    /**
      * Sets the value of the 'actor' field.
      * @param value The value of 'actor'.
      * @return This builder.
      */
    public test.prof.events.ProfileEventHeader.Builder setActor(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.actor = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'actor' field has been set.
      * @return True if the 'actor' field has been set, false otherwise.
      */
    public boolean hasActor() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'actor' field.
      * @return This builder.
      */
    public test.prof.events.ProfileEventHeader.Builder clearActor() {
      actor = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'source' field.
      * @return The value.
      */
    public java.lang.CharSequence getSource() {
      return source;
    }


    /**
      * Sets the value of the 'source' field.
      * @param value The value of 'source'.
      * @return This builder.
      */
    public test.prof.events.ProfileEventHeader.Builder setSource(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.source = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'source' field has been set.
      * @return True if the 'source' field has been set, false otherwise.
      */
    public boolean hasSource() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'source' field.
      * @return This builder.
      */
    public test.prof.events.ProfileEventHeader.Builder clearSource() {
      source = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'eventType' field.
      * @return The value.
      */
    public java.lang.CharSequence getEventType() {
      return eventType;
    }


    /**
      * Sets the value of the 'eventType' field.
      * @param value The value of 'eventType'.
      * @return This builder.
      */
    public test.prof.events.ProfileEventHeader.Builder setEventType(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.eventType = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'eventType' field has been set.
      * @return True if the 'eventType' field has been set, false otherwise.
      */
    public boolean hasEventType() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'eventType' field.
      * @return This builder.
      */
    public test.prof.events.ProfileEventHeader.Builder clearEventType() {
      eventType = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'eventTypeVersion' field.
      * @return The value.
      */
    public java.lang.CharSequence getEventTypeVersion() {
      return eventTypeVersion;
    }


    /**
      * Sets the value of the 'eventTypeVersion' field.
      * @param value The value of 'eventTypeVersion'.
      * @return This builder.
      */
    public test.prof.events.ProfileEventHeader.Builder setEventTypeVersion(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.eventTypeVersion = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'eventTypeVersion' field has been set.
      * @return True if the 'eventTypeVersion' field has been set, false otherwise.
      */
    public boolean hasEventTypeVersion() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'eventTypeVersion' field.
      * @return This builder.
      */
    public test.prof.events.ProfileEventHeader.Builder clearEventTypeVersion() {
      eventTypeVersion = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ProfileEventHeader build() {
      try {
        ProfileEventHeader record = new ProfileEventHeader();
        record.headerVersion = fieldSetFlags()[0] ? this.headerVersion : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.messageId = fieldSetFlags()[1] ? this.messageId : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.aggregateId = fieldSetFlags()[2] ? this.aggregateId : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.occurrenceDate = fieldSetFlags()[3] ? this.occurrenceDate : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.actor = fieldSetFlags()[4] ? this.actor : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.source = fieldSetFlags()[5] ? this.source : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.eventType = fieldSetFlags()[6] ? this.eventType : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.eventTypeVersion = fieldSetFlags()[7] ? this.eventTypeVersion : (java.lang.CharSequence) defaultValue(fields()[7]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ProfileEventHeader>
    WRITER$ = (org.apache.avro.io.DatumWriter<ProfileEventHeader>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ProfileEventHeader>
    READER$ = (org.apache.avro.io.DatumReader<ProfileEventHeader>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.headerVersion);

    out.writeString(this.messageId);

    out.writeString(this.aggregateId);

    out.writeString(this.occurrenceDate);

    out.writeString(this.actor);

    out.writeString(this.source);

    out.writeString(this.eventType);

    out.writeString(this.eventTypeVersion);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.headerVersion = in.readString(this.headerVersion instanceof Utf8 ? (Utf8)this.headerVersion : null);

      this.messageId = in.readString(this.messageId instanceof Utf8 ? (Utf8)this.messageId : null);

      this.aggregateId = in.readString(this.aggregateId instanceof Utf8 ? (Utf8)this.aggregateId : null);

      this.occurrenceDate = in.readString(this.occurrenceDate instanceof Utf8 ? (Utf8)this.occurrenceDate : null);

      this.actor = in.readString(this.actor instanceof Utf8 ? (Utf8)this.actor : null);

      this.source = in.readString(this.source instanceof Utf8 ? (Utf8)this.source : null);

      this.eventType = in.readString(this.eventType instanceof Utf8 ? (Utf8)this.eventType : null);

      this.eventTypeVersion = in.readString(this.eventTypeVersion instanceof Utf8 ? (Utf8)this.eventTypeVersion : null);

    } else {
      for (int i = 0; i < 8; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.headerVersion = in.readString(this.headerVersion instanceof Utf8 ? (Utf8)this.headerVersion : null);
          break;

        case 1:
          this.messageId = in.readString(this.messageId instanceof Utf8 ? (Utf8)this.messageId : null);
          break;

        case 2:
          this.aggregateId = in.readString(this.aggregateId instanceof Utf8 ? (Utf8)this.aggregateId : null);
          break;

        case 3:
          this.occurrenceDate = in.readString(this.occurrenceDate instanceof Utf8 ? (Utf8)this.occurrenceDate : null);
          break;

        case 4:
          this.actor = in.readString(this.actor instanceof Utf8 ? (Utf8)this.actor : null);
          break;

        case 5:
          this.source = in.readString(this.source instanceof Utf8 ? (Utf8)this.source : null);
          break;

        case 6:
          this.eventType = in.readString(this.eventType instanceof Utf8 ? (Utf8)this.eventType : null);
          break;

        case 7:
          this.eventTypeVersion = in.readString(this.eventTypeVersion instanceof Utf8 ? (Utf8)this.eventTypeVersion : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










